defaults:
  pin: ${ pin | default({}) }
  pin_mode: ${ pin.get("mode", {}) }

number: ${ pin.get("number", "GPIO0") }
inverted: ${ pin.get("inverted", false) }
allow_other_uses: ${ pin.get("allow_other_uses", false) }
mode:
  input: ${ pin_mode.get("input", false) }
  output: ${ pin_mode.get("output", false) }
  pullup: ${ pin_mode.get("pullup", false) }
  pulldown: ${ pin_mode.get("pulldown", false) }
  open_drain: ${ pin_mode.get("open_drain", false) }
# esp32 specific:
drive_strength: ${ pin.get("drive_strength", "20mA") }
ignore_strapping_warning: ${ pin.get("ignore_strapping_warning", false) }
ignore_pin_validation_error: ${ pin.get("ignore_pin_validation_error", false) }
