defaults:
  input: ${ input | default({}) }
  input_config: ${ input.get("config", {}) }

binary_sensor:
  - platform: gpio
    name: ${ input_config.get("name", input.get("name")) }
    id: ${ input.get("id") }
    internal: ${ input_config.get("internal", false) }
    disabled_by_default: ${ input_config.get("disabled_by_default", false) }
    pin:
      pcf8574: inputs
      number: ${ input.get("number") }
      mode: INPUT
      inverted: true
    use_interrupt: false
