sensor:
  - platform: internal_temperature
    name: MCU Temperature
    id: mcu_temperature
    device_class: temperature
    unit_of_measurement: °C
    accuracy_decimals: 0
    state_class: measurement
    entity_category: diagnostic
    disabled_by_default: true
    filters:
      - delta: 1
