substitutions:
  firmware_family: esphome
  eth_type: LAN8720 # LAN8720 | RTL8201 | DP83848 | IP101 | JL1101 | KSZ8081 | KSZ8081RNA | W5500 | OPENETH | DM9051 | LAN8670
  eth_mdc_pin: GPIO23
  eth_mdc_strapping: false
  eth_mdio_pin: GPIO18
  eth_mdio_strapping: false
  eth_clk_pin: GPIO0
  eth_clk_strapping: true
  eth_clk_mode: CLK_EXT_IN # CLK_EXT_IN | CLK_OUT
  eth_power_pin: ''
  eth_power_strapping: false
  eth_phy_addr: 1

packages:
  - ${ networking_mode == 'ethernet' and eth_power_pin and net_eth_power_module or {} }

ethernet:
  type: ${eth_type}
  mdc_pin: ${ {'number':eth_mdc_pin,'ignore_strapping_warning':eth_mdc_strapping} if firmware_family=='esphome' else {'number':eth_mdc_pin} }
  mdio_pin: ${ {'number':eth_mdio_pin,'ignore_strapping_warning':eth_mdio_strapping} if firmware_family=='esphome' else {'number':eth_mdio_pin} }
  clk:
    pin: ${ {'number':eth_clk_pin,'ignore_strapping_warning':eth_clk_strapping} if firmware_family=='esphome' else {'number':eth_clk_pin} }
    mode: ${eth_clk_mode}
  phy_addr: ${eth_phy_addr}

text_sensor:
  - platform: ethernet_info
    ip_address:
      name: IP Address
      id: mcu_ip_address
      entity_category: diagnostic
      icon: mdi:ip-network
    mac_address:
      name: MAC Address
      id: mcu_mac_address
      entity_category: diagnostic
      disabled_by_default: true
      icon: mdi:lan
