substitutions:
  # Home Assistant light entity to control (override this from the main device YAML)
  ha_light_entity: light.example_light

packages:
  Base: github://ngorchilov/esphome-lib/packages/modules/relay-control-light-magic.yaml

magic_switch:
  id: !extend rocker_switch
  on_switch:
    - homeassistant.action:
        action: light.toggle
        data:
          entity_id: ${ha_light_entity}
