substitutions:
  rocker_pin: GPIO14 # S1/S2 rocker switch pin (onoff1)
  rocker_inverted: true
  rocker_strapping: false

packages:
  Base: github://ngorchilov/esphome-lib/packages/modules/relay-control-switch.yaml

switch:
  - id: !extend relay_switch
    internal: true
    # Keep the light entity in sync even when the relay is toggled locally (rocker/button/on_boot).
    # Note: declaring on_turn_on/off here may override the base package triggers, so we restate LED sync too.
    on_turn_on:
      - light.turn_on: relay_light
      - light.turn_on: relay_led
    on_turn_off:
      - light.turn_off: relay_light
      - light.turn_off: relay_led

binary_sensor:
  - platform: gpio
    name: Rocker Switch
    id: rocker_switch
    pin:
      number: ${rocker_pin}
      mode:
        input: true
        pullup: ${rocker_inverted}
        pulldown: ${not rocker_inverted}
      inverted: ${rocker_inverted}
      ignore_strapping_warning: ${rocker_strapping}
    on_state:
      then:
        - switch.toggle: relay_switch

output:
  - platform: template
    id: light_output
    type: binary
    write_action:
      - if:
          condition:
            lambda: return state;
          then:
            - switch.turn_on: relay_switch
          else:
            - switch.turn_off: relay_switch

light:
  - platform: binary
    id: relay_light
    name: None
    output: light_output
    restore_mode: RESTORE_DEFAULT_OFF
