substitutions:
  # Home Assistant light entity to control (override this from the main device YAML)
  ha_light_entity: light.example_light

packages:
  Base: github://ngorchilov/esphome-lib/packages/modules/relay-control-light.yaml

binary_sensor:
  - !extend rocker_switch
    on_state:
      then:
        - homeassistant.action:
            action: light.toggle
            data:
              entity_id: ${ha_light_entity}