defaults:
  networking: ${ networking | default({}) }
  networking_wifi: ${ networking.get("wifi", {}) }
  _wifi_default_ssid: !secret wifi_ssid
  _wifi_default_password: !secret wifi_password
  wifi_ssid: ${ networking_wifi.get("ssid", _wifi_default_ssid) }
  wifi_password: ${ networking_wifi.get("password", _wifi_default_password) }
  ap_ssid: ${ networking_wifi.get("ap_ssid", "ESPHome-" ~ (name | default("base-board"))) }

wifi:
  ssid: ${wifi_ssid}
  password: ${wifi_password}

  ap:
    ssid: ${ap_ssid}

captive_portal:

sensor:
  - platform: wifi_signal
    name: WiFi Signal
    id: mcu_wifi_signal
    device_class: signal_strength
    unit_of_measurement: dBm
    accuracy_decimals: 0
    state_class: measurement
    entity_category: diagnostic
    disabled_by_default: true
    filters:
      - delta: 1

text_sensor:
  - platform: wifi_info
    ip_address:
      name: IP
      id: mcu_ip
      entity_category: diagnostic
    ssid:
      name: SSID
      id: mcu_ssid
      entity_category: diagnostic
      disabled_by_default: true
    bssid:
      name: BSSID
      id: mcu_bssid
      entity_category: diagnostic
      disabled_by_default: true
    mac_address:
      name: MAC Address
      id: mcu_mac_address
      entity_category: diagnostic
      disabled_by_default: true
