substitutions:
  name: base-board-esp07
  friendly_name: Base Board ESP07

packages:
  Base: github://ngorchilov/esphome-lib/packages/boards/templates/base-board-esphome-esp8266.yaml

esp8266:
  board: esp07
