substitutions:
  name: base-board-esp32-c6-devkitc-1
  friendly_name: Base Board ESP32-C6-DevKitC-1

packages:
  Base: github://ngorchilov/esphome-lib/packages/boards/templates/base-board-esphome-esp32.yaml

esp32:
  board: esp32-c6-devkitc-1
  variant: esp32c6
