substitutions:
  name: base-board-heltec-wifi-lora-32-v2
  friendly_name: Base Board Heltec WiFi LoRa 32 V2

defaults:
  esp32_classic:
    minimum_chip_revision: 3.1
    sram1_as_iram: true

packages:
  - !include ../templates/base-board-esphome-esp32-classic.yaml

esp32:
  board: heltec_wifi_lora_32_V2
