substitutions:
  name: base-board-lilygo-ttgo-lora32-v21
  friendly_name: Base Board LilyGO TTGO LoRa32 V2.1

packages:
  - !include ../templates/base-board-esphome-esp32.yaml

esp32:
  board: ttgo-lora32-v21
  framework:
    type: esp-idf
    advanced:
      sram1_as_iram: true
