substitutions:
  name: base-board-nodemcu-32s
  friendly_name: Base Board NodeMCU-32S

packages:
  Base: github://ngorchilov/esphome-lib/packages/boards/templates/base-board-esphome-esp32.yaml

esp32:
  board: nodemcu-32s
