substitutions:
  name: grundfos-lc-231
  friendly_name: Grundfos LC-231
  grundfos_mac_address: E4:52:1E:B2:01:6A

packages:
  board:
    url: https://github.com/ngorchilov/esphome-lib
    files:
      - devices/m5stack-poesp32.yaml
    # refresh: 0s

esp32_ble_tracker:

ble_client:
  - mac_address: ${grundfos_mac_address}
    id: ble_client_id

text_sensor:
  - platform: ble_client
    name: Manufacturer
    ble_client_id: ble_client_id
    service_uuid: 180A
    characteristic_uuid: 2A29
    entity_category: diagnostic
    # filters:
    #   - lambda: |-
    #       if (x == "")
    #         return {};
    #       else
    #         return x;

  - platform: ble_client
    name: Model Number
    ble_client_id: ble_client_id
    service_uuid: 180A
    characteristic_uuid: 2A24
    entity_category: diagnostic
    # filters:
    #   - lambda: |-
    #       if (x == "")
    #         return {};
    #       else
    #         return x;

  - platform: ble_client
    name: Hardware Revision
    ble_client_id: ble_client_id
    service_uuid: 180A
    characteristic_uuid: 2A27
    entity_category: diagnostic
    # filters:
    #   - lambda: |-
    #       if (x == "")
    #         return {};
    #       else
    #         return x;

  - platform: ble_client
    name: Firmware Revision
    ble_client_id: ble_client_id
    service_uuid: 180A
    characteristic_uuid: 2A26
    entity_category: diagnostic
    # filters:
    #   - lambda: |-
    #       if (x == "")
    #         return {};
    #       else
    #         return x;

  - platform: ble_client
    name: Software Revision
    ble_client_id: ble_client_id
    service_uuid: 180A
    characteristic_uuid: 2A28
    entity_category: diagnostic
    # filters:
    #   - lambda: |-
    #       if (x == "")
    #         return {};
    #       else
    #         return x;
