substitutions:
  name: heltec-hri-485x
  friendly_name: Heltec HRI-485X

packages:
  - !include
    file: ../packages/appliances/heltec-hri-485x.yaml
    vars:
      hri485x: ${ hri485x | default({}) }

logger:
  level: DEBUG
