substitutions:
  name: kincony-kc868-a6
  friendly_name: KinCony KC868-A6

packages:
  - !include
    file: ../packages/appliances/kincony-kc868-a6.yaml
    vars:
      kincony_kc868_a6: ${ kincony_kc868_a6 | default({}) }
      esp32_advanced: ${ esp32_advanced | default({}) }
