substitutions:
  name: m5stack-poesp32
  friendly_name: M5Stack PoESP32

packages:
  - !include
    file: ../packages/boards/espressif/m5stack-core-esp32.yaml
    vars:
      networking:
        mode: ethernet
        ethernet:
          type: IP101
          mdc_pin: GPIO23
          mdc_strapping: false
          mdio_pin: GPIO18
          mdio_strapping: false
          clk_pin: GPIO0
          clk_strapping: true
          power_pin: GPIO5
          power_strapping: true
          phy_addr: 1

esphome:
  project:
    name: M5Stack.PoESP32
    version: 1.0.0

dashboard_import:
  package_import_url: github://ngorchilov/esphome-lib/devices/m5stack-poesp32.yaml
  import_full_config: false
