substitutions:
  name: m5stack-poesp32
  friendly_name: M5Stack PoESP32

  networking_mode: ethernet
  eth_type: IP101
  eth_mdc_pin: GPIO23
  eth_mdc_strapping: false
  eth_mdio_pin: GPIO18
  eth_mdio_strapping: false
  eth_clk_pin: GPIO0
  eth_clk_strapping: true
  eth_power_pin: GPIO5
  eth_power_strapping: true
  eth_phy_addr: 1

packages:
  - !include ../packages/boards/espressif/m5stack-core-esp32.yaml

esphome:
  project:
    name: M5Stack.PoESP32
    version: 1.0.0

dashboard_import:
  package_import_url: github://ngorchilov/esphome-lib/devices/m5stack-poesp32.yaml
  import_full_config: false
