substitutions:
  name: sonoff-basic-r4
  friendly_name: Sonoff BASIC R4

  relay_pin: GPIO4
  relay_inverted: false
  relay_strapping: false

  button_pin: GPIO9
  button_inverted: true
  button_strapping: true

  led_pin: GPIO6
  led_inverted: false
  led_strapping: false

  rocker_pin: GPIO5 # Sonoff Magic Switch
  rocker_inverted: false
  rocker_strapping: false
  rocker_timeout: 1ms

  ha_light_entity: light.light_group_master

packages:
  Board: github://ngorchilov/esphome-lib/packages/boards/espressif/esp32-c3-devkitm-1.yaml
  WiFi: github://ngorchilov/esphome-lib/packages/modules/wifi.yaml
  Relay: github://ngorchilov/esphome-lib/packages/modules/relay-control-smart-light-magic.yaml

switch:
  - platform: template
    name: Do Not Disturb
    id: dnd_mode
    optimistic: true
    restore_mode: RESTORE_DEFAULT_OFF
# magic_switch:
#   id: !extend rocker_switch
#   on_switch:
#     condition:
#       - lambda: 'return !id(dnd_mode).state;'
#     then:
#       - homeassistant.action:
#           action: light.toggle
#           data:
#             entity_id: ${ha_light_entity}
#       - binary_sensor.template.publish:
#           id: rocker_switch_virtual
#           state: !lambda 'return !id(rocker_switch_virtual).state;'
