substitutions:
  name: sonoff-basic-r4
  friendly_name: Sonoff BASIC R4

  relay_pin: GPIO4
  relay_inverted: false
  relay_strapping: false

  button_pin: GPIO9
  button_inverted: true
  button_strapping: true

  led_pin: GPIO6
  led_inverted: false
  led_strapping: false

  rocker_pin: GPIO5 # Sonoff Magic Switch
  rocker_inverted: false
  rocker_strapping: false

packages:
  - !include ../packages/boards/espressif/esp32-c3-devkitm-1.yaml
  - !include
    file: ../packages/modules/relay-control.yaml
    vars:
      rc:
        id: sbr4
        name: none
        power:
          pin: ${relay_pin}
          inverted: ${relay_inverted}
          strapping: ${relay_strapping}
        control:
          mode: local
        indicator_led:
          enabled: true
          pin: ${led_pin}
          inverted: ${led_inverted}
          strapping: ${led_strapping}
        integrated_button:
          enabled: true
          pin: ${button_pin}
          inverted: ${button_inverted}
          strapping: ${button_strapping}
        external_switch:
          enabled: true
          pin: ${rocker_pin}
          inverted: ${rocker_inverted}
          strapping: ${rocker_strapping}
          mode: rocker

esphome:
  project:
    name: SONOFF.BASICR4
    version: 1.0.0
