substitutions:
  name: tuya-strip-3x2-cb2s
  friendly_name: Tuya Strip 3x2 (CB2S)

  led_pin: GPIO10
  led_inverted: 'true'

  button_pin: GPIO11
  button_pullup: 'true'
  button_inverted: 'true'

  relay1_pin: GPIO6
  relay1_inverted: 'false'
  relay1_id: socket_1_2
  relay1_name: Socket 1&2

  relay2_pin: GPIO7
  relay2_inverted: 'false'
  relay2_id: socket_3_4
  relay2_name: Socket 3&4

  relay3_pin: GPIO8
  relay3_inverted: 'false'
  relay3_id: socket_5_6
  relay3_name: Socket 5&6

  relay4_pin: GPIO26
  relay4_inverted: 'false'
  relay4_id: relay_usb
  relay4_name: Relay USB

  relay_reboot_delay: 10s

packages:
  - !include ../packages/boards/tuya/cb2s.yaml
esphome:
  on_boot:
    - if:
        condition:
          binary_sensor.is_on: power_status
        then:
          - light.turn_on: status_led
        else:
          - light.turn_off: status_led

web_server:
  version: 3

output:
  - platform: gpio
    id: led_output
    pin: ${led_pin}
    inverted: ${led_inverted}

light:
  - platform: binary
    id: status_led
    output: led_output

binary_sensor:
  - platform: template
    id: power_status
    name: Power Status
    lambda: |-
      return id(${relay1_id}).state || id(${relay2_id}).state ||
             id(${relay3_id}).state || id(${relay4_id}).state;
    on_state:
      then:
        - if:
            condition:
              binary_sensor.is_on: power_status
            then:
              - light.turn_on: status_led
            else:
              - light.turn_off: status_led

  - platform: gpio
    name: Button
    pin:
      number: ${button_pin}
      mode:
        input: true
        pullup: ${button_pullup}
      inverted: ${button_inverted}
    on_press:
      then:
        - if:
            condition:
              binary_sensor.is_on: power_status
            then:
              - switch.turn_off: ${relay1_id}
              - switch.turn_off: ${relay2_id}
              - switch.turn_off: ${relay3_id}
              - switch.turn_off: ${relay4_id}
            else:
              - switch.turn_on: ${relay1_id}
              - switch.turn_on: ${relay2_id}
              - switch.turn_on: ${relay3_id}
              - switch.turn_on: ${relay4_id}

switch:
  - platform: gpio
    name: ${relay1_name}
    id: ${relay1_id}
    pin:
      number: ${relay1_pin}
      inverted: ${relay1_inverted}
    restore_mode: RESTORE_DEFAULT_OFF

  - platform: gpio
    name: ${relay2_name}
    id: ${relay2_id}
    pin:
      number: ${relay2_pin}
      inverted: ${relay2_inverted}
    restore_mode: RESTORE_DEFAULT_OFF

  - platform: gpio
    name: ${relay3_name}
    id: ${relay3_id}
    pin:
      number: ${relay3_pin}
      inverted: ${relay3_inverted}
    restore_mode: RESTORE_DEFAULT_OFF

  - platform: gpio
    name: ${relay4_name}
    id: ${relay4_id}
    pin:
      number: ${relay4_pin}
      inverted: ${relay4_inverted}
    restore_mode: RESTORE_DEFAULT_OFF

button:
  - platform: template
    name: Reboot ${relay1_name}
    on_press:
      - switch.turn_off: ${relay1_id}
      - delay: ${relay_reboot_delay}
      - switch.turn_on: ${relay1_id}

  - platform: template
    name: Reboot ${relay2_name}
    on_press:
      - switch.turn_off: ${relay2_id}
      - delay: ${relay_reboot_delay}
      - switch.turn_on: ${relay2_id}

  - platform: template
    name: Reboot ${relay3_name}
    on_press:
      - switch.turn_off: ${relay3_id}
      - delay: ${relay_reboot_delay}
      - switch.turn_on: ${relay3_id}

  - platform: template
    name: Reboot ${relay4_name}
    on_press:
      - switch.turn_off: ${relay4_id}
      - delay: ${relay_reboot_delay}
      - switch.turn_on: ${relay4_id}

  - platform: template
    name: Reboot All Relays
    on_press:
      - switch.turn_off: ${relay1_id}
      - switch.turn_off: ${relay2_id}
      - switch.turn_off: ${relay3_id}
      - switch.turn_off: ${relay4_id}
      - delay: ${relay_reboot_delay}
      - switch.turn_on: ${relay1_id}
      - switch.turn_on: ${relay2_id}
      - switch.turn_on: ${relay3_id}
      - switch.turn_on: ${relay4_id}
