substitutions:
  name: tuya-ceiling-light-v2-cbu
  friendly_name: Tuya Ceiling Light V2 (CBU)
  chip: cbu

packages:
  - !include
    file: ../packages/appliances/tuya-ceiling-light-v2.yaml
    vars:
      ceiling_light:
        chip: ${chip}
