substitutions:
  name: tuya-dry-relay-2dc-10a
  friendly_name: Tuya Dry Relay 2DC 10A

  relay1_pin: GPIO14
  relay1_inverted: 'false'
  button1_pin: GPIO9
  button1_inverted: 'true'

  relay2_pin: GPIO6
  relay2_inverted: 'false'
  button2_pin: GPIO24
  button2_inverted: 'true'

  master_switch_pin: GPIO8
  master_switch_inverted: 'true'
  master_switch_pullup: 'true'

  status_led_pin: GPIO26
  status_led_inverted: 'true'

  rf433_pin: GPIO7
  rf433_inverted: 'false'

packages:
  - !include ../packages/boards/tuya/cb3s.yaml
  - !include
    file: ../packages/modules/remote-receiver-rc-switch.yaml
    vars:
      receiver:
        enabled: ${ (rf433 | default({})).get("enabled", false) }
        id: rf433_receiver
        pin: ${rf433_pin}
        inverted: ${rf433_inverted}
        buffer_size: ${ (rf433 | default({})).get("buffer_size", "4kb") }
        filter: ${ (rf433 | default({})).get("filter", "150us") }
        idle: ${ (rf433 | default({})).get("idle", "4ms") }
  - !include
    file: ../packages/modules/relay-control.yaml
    vars:
      rc:
        id: relay_1
        entity: '${ relay_1_entity | default({"type": "switch", "name": "Relay 1"}) }'
        power:
          pin: ${relay1_pin}
          inverted: ${relay1_inverted}
        control:
          mode: local
        integrated_button:
          enabled: true
          name: Button 1
          pin: ${button1_pin}
          inverted: ${button1_inverted}
  - !include
    file: ../packages/modules/relay-control.yaml
    vars:
      rc:
        id: relay_2
        entity: '${ relay_2_entity | default({"type": "switch", "name": "Relay 2"}) }'
        power:
          pin: ${relay2_pin}
          inverted: ${relay2_inverted}
        control:
          mode: local
        integrated_button:
          enabled: true
          name: Button 2
          pin: ${button2_pin}
          inverted: ${button2_inverted}

binary_sensor:
  - platform: gpio
    name: Master Switch
    id: master_switch
    pin:
      number: ${master_switch_pin}
      inverted: ${master_switch_inverted}
      mode:
        input: true
        pullup: ${master_switch_pullup}
    on_click:
      - if:
          condition:
            lambda: |-
              return id(relay_1_power_relay).state || id(relay_2_power_relay).state;
          then:
            - script.execute: relay_1_power_off
            - script.execute: relay_2_power_off
          else:
            - script.execute: relay_1_power_on
            - script.execute: relay_2_power_on

status_led:
  pin:
    number: ${status_led_pin}
    inverted: ${status_led_inverted}
