substitutions:
  name: tuya-socket-1pm-cbu
  friendly_name: Tuya Socket 1PM (CBU)

packages:
  - !include ../packages/boards/tuya/cbu.yaml
  - !include
    file: ../packages/modules/relay-control.yaml
    vars:
      rc:
        id: relay
        entity: ${ entity | default({}) }
        power:
          pin: GPIO6
          inverted: false
        control:
          mode: local
        indicator_led:
          enabled: true
          pin: GPIO7
          inverted: false
        integrated_button:
          enabled: true
          pin: GPIO24
          inverted: true
  - !include
    file: ../packages/modules/energy-monitoring-bl0937.yaml
    vars:
      energy:
        cf_pin: GPIO20
        cf1_pin: GPIO8
        sel_pin: GPIO9
        voltage_divider: 785
        current_resistor: 0.00102 ohm
        current_multiply: 4.45
        update_interval: 30s
