substitutions:
  name: tuya-mini-switch-1pm-16a
  friendly_name: Tuya Mini Switch 1PM 16A

packages:
  - !include ../packages/boards/tuya/cb2s.yaml
  - !include
    file: ../packages/modules/relay-control.yaml
    vars:
      rc:
        id: relay
        entity: ${ entity | default({}) }
        power:
          pin: GPIO7
          inverted: false
        control:
          mode: local
        indicator_led:
          enabled: true
          pin: GPIO26
          inverted: true
        integrated_button:
          enabled: true
          pin: GPIO24
          inverted: true
        external_switch:
          enabled: true
          pin: GPIO6
          inverted: true
          mode: rocker
  - !include
    file: ../packages/modules/energy-monitoring-bl0942.yaml
    vars:
      energy:
        rx_pin: GPIO10
        tx_pin: GPIO11
