substitutions:
  name: base-board-libretiny
  friendly_name: Base Board LibreTiny

  firmware_family: libretiny

packages:
  - !include base-board.yaml

text_sensor:
  - id: !extend mcu_active_firmware_image
    internal: false
    lambda: |-
      extern unsigned char current_ota_slot() asm("lt_ota_dual_get_current");
      switch (current_ota_slot()) {
        case 0:
          return {"Single"};
        case 1:
          return {"First"};
        case 2:
          return {"Second"};
        default:
          return {"Unknown"};
      }

  - platform: libretiny
    version:
      name: LibreTiny Version
      id: mcu_version_libretiny
      entity_category: diagnostic
      disabled_by_default: true
