substitutions:
  name: base-board-esphome-esp8266
  friendly_name: Base Board ESPHome (ESP8266)

packages:
  - !include base-board-esphome.yaml

logger:
  baud_rate: 0

sensor:
  - id: !remove mcu_temperature # not available in esp8266

text_sensor:
  - platform: template
    name: Active Firmware Image
    id: mcu_active_firmware_image
    entity_category: diagnostic
    disabled_by_default: true
    update_interval: 30s
    lambda: return {"Single"};
