substitutions:
  name: base-board
  friendly_name: Base Board

  log_level: INFO
  has_internal_temperature: true
  internal_temperature_module: !include ../../modules/internal-temperature.yaml

packages:
  - !include ../../modules/networking.yaml
  - ${ has_internal_temperature and internal_temperature_module or {} }

esphome:
  name: ${name}
  friendly_name: ${friendly_name}

  # Requires conditional packages and reliable !include vars substitution in lambdas.
  min_version: 2026.5.0

  on_boot:
    - priority: 500
      then:
        - component.update: mcu_active_firmware_image

logger:
  level: ${log_level}

button:
  - platform: restart
    name: MCU Restart
    id: mcu_restart

sensor:
  - platform: uptime
    type: timestamp
    name: Uptime
    id: mcu_uptime
    time_id: ha_time
    device_class: uptime
    entity_category: diagnostic

binary_sensor:
  - platform: status
    name: Status
    id: mcu_status
    device_class: connectivity
    entity_category: diagnostic
    disabled_by_default: true

text_sensor:
  - platform: template
    name: Active Firmware Image
    id: mcu_active_firmware_image
    internal: true
    entity_category: diagnostic
    disabled_by_default: true
    update_interval: never

  - platform: version
    name: ESPhome Version
    id: mcu_version_esphome
    entity_category: diagnostic
    hide_timestamp: true
    disabled_by_default: true

time:
  - platform: homeassistant
    id: ha_time
