substitutions:
  name: base-board-esphome-esp8266
  friendly_name: Base Board ESPHome (ESP8266)

packages:
  - !include base-board-esphome.yaml

logger:
  baud_rate: 0

sensor:
  - id: !remove mcu_temperature # not available in esp8266

text_sensor:
  - id: !extend mcu_active_firmware_image
    internal: false
    lambda: return {"Single"};
