substitutions:
  name: base-board
  friendly_name: Base Board

  log_level: INFO

packages:
  - !include ../../modules/networking.yaml

esphome:
  name: ${name}
  friendly_name: ${friendly_name}

  # 2025.12.0: Conditional Package Inclusion (https://esphome.io/changelog/2025.12.0/#conditional-package-inclusion)
  min_version: 2025.12.0

logger:
  level: ${log_level}

button:
  - platform: restart
    name: MCU Restart
    id: mcu_restart

sensor:
  - platform: uptime
    type: timestamp
    name: Uptime
    id: mcu_uptime
    time_id: ha_time
    device_class: uptime
    entity_category: diagnostic

  - platform: internal_temperature
    name: MCU Temperature
    id: mcu_temperature
    device_class: temperature
    unit_of_measurement: °C
    accuracy_decimals: 0
    state_class: measurement
    entity_category: diagnostic
    disabled_by_default: true
    filters:
      - delta: 1

binary_sensor:
  - platform: status
    name: Status
    id: mcu_status
    device_class: connectivity
    entity_category: diagnostic
    disabled_by_default: true

text_sensor:
  - platform: version
    name: ESPhome Version
    id: mcu_version_esphome
    entity_category: diagnostic
    hide_timestamp: true
    disabled_by_default: true

time:
  - platform: homeassistant
    id: ha_time
