# Optional integrated push button
# Always toggles POWER relay (safety / hardwired behavior).

defaults:
  rc: ${ rc | default({}) }
  rc_integrated_button: ${ rc.get("integrated_button", {}) }

  rc_id: ${ rc.get("id", "rc1") }

  button_pin: ${ rc_integrated_button.get("pin", "GPIO0") }
  button_inverted: ${ rc_integrated_button.get("inverted", true) }
  button_strapping: ${ rc_integrated_button.get("strapping", false) }
  button_internal: ${ rc_integrated_button.get("internal", false) }

binary_sensor:
  - platform: gpio
    name: ${rc_id} Integrated Button
    id: ${rc_id}_integrated_button
    internal: ${button_internal}
    pin: !include
      file: ../../pin.yaml
      vars:
        pin:
          number: ${button_pin}
          inverted: ${button_inverted}
          mode:
            input: true
            pullup: ${button_inverted}
            pulldown: ${not button_inverted}
          ignore_strapping_warning: ${button_strapping}
    on_click:
      - script.execute: ${rc_id}_power_toggle
